/**
 * Turns MakeCode Arcade's compiled API metadata into Blockly block definitions
 * and a toolbox, so the editor renders real Arcade blocks — `sprite of kind`,
 * `on game update`, `move with buttons` — instead of generic placeholders.
 *
 * pxt has already parsed every block's layout into `attributes._def`, so this
 * translates that structure rather than re-parsing TypeScript annotations.
 *
 * Reads  .arcade-cache/target.json   (see scripts/fetchArcade.mjs)
 * Writes media/generated/arcade-blocks.json, arcade-toolbox.json, arcade-meta.json
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(root, 'media', 'generated');

/** pxt SymbolKind values this script cares about. */
const KIND_MODULE = 5;
const KIND_ENUM = 6;

const DEFAULT_COLOUR = '#7B8794';

const target = JSON.parse(await readFile(join(root, '.arcade-cache', 'target.json'), 'utf8'));

/** Every API symbol across all bundled packages, keyed by qualified name. */
const symbols = {};
for (const info of Object.values(target.apiInfo ?? {})) {
  Object.assign(symbols, info.apis?.byQName ?? {});
}
if (Object.keys(symbols).length === 0) {
  throw new Error('target bundle contained no API metadata');
}

const namespaces = collectNamespaces(symbols);
const { blocks, entries, skipped } = buildBlocks(symbols, namespaces);
const enums = buildEnumBlocks(symbols, namespaces);
blocks.push(...enums);
const extras = buildFallbackShadows(blocks, entries);
const toolbox = buildToolbox(entries, namespaces);

await mkdir(OUT, { recursive: true });
await writeFile(join(OUT, 'arcade-blocks.json'), JSON.stringify([...blocks, ...extras], null, 0));
await writeFile(join(OUT, 'arcade-toolbox.json'), JSON.stringify(toolbox, null, 0));
await writeFile(
  join(OUT, 'arcade-meta.json'),
  JSON.stringify(
    {
      target: target.id,
      targetVersion: target.versions?.target ?? null,
      pxtVersion: target.versions?.pxt ?? null,
      generatedBlocks: blocks.length,
      fallbackShadows: extras.length,
      categories: toolbox.length,
      note: 'Generated by scripts/generateArcadeBlocks.mjs from the MakeCode Arcade target bundle.',
    },
    null,
    2
  )
);

console.log(`blocks:     ${blocks.length} (incl. ${enums.length} enum/kind dropdowns)`);
console.log(`fallbacks:  ${extras.length}`);
console.log(`categories: ${toolbox.length}`);
console.log(`skipped:    ${skipped.length}`);

/** Namespaces carry the category colour, icon, ordering and group names. */
function collectNamespaces(all) {
  const found = new Map();
  for (const [qName, symbol] of Object.entries(all)) {
    if (symbol.kind !== KIND_MODULE || qName.includes('.')) {
      continue;
    }
    const attrs = symbol.attributes ?? {};
    found.set(qName, {
      name: qName,
      label: attrs.block ?? capitalize(qName),
      colour: attrs.color ?? DEFAULT_COLOUR,
      icon: attrs.icon ?? '',
      weight: attrs.weight ?? 50,
      advanced: Boolean(attrs.advanced),
      groups: attrs.groups ?? [],
      help: attrs.help ?? '',
    });
  }
  return found;
}

function buildBlocks(all, namespaceMap) {
  const blocks = [];
  const entries = [];
  const skipped = [];

  for (const [qName, symbol] of Object.entries(all)) {
    const attrs = symbol.attributes;
    if (!attrs?.blockId || !attrs.block || !attrs._def) {
      continue;
    }

    const namespaceName = attrs.blockNamespace ?? qName.split('.')[0];
    const namespace = namespaceMap.get(namespaceName);
    const colour = attrs.color ?? namespace?.colour ?? DEFAULT_COLOUR;

    try {
      const block = defineBlock(qName, symbol, attrs, colour, all);
      blocks.push(block.definition);
      entries.push({
        type: attrs.blockId,
        namespace: namespaceName,
        group: attrs.group ?? '',
        weight: attrs.weight ?? 50,
        // Deprecated and hidden blocks are still *defined*, so existing files
        // that use them keep rendering — they are only left out of the toolbox.
        listed: !attrs.blockHidden && !attrs.deprecated && !attrs.debug,
        shadows: block.shadows,
        fields: block.fieldDefaults,
      });
    } catch (error) {
      skipped.push({ qName, reason: error.message });
    }
  }

  return { blocks, entries, skipped };
}

/**
 * Translates one pxt block definition into Blockly JSON.
 *
 * `_expandedDef` holds the parts MakeCode hides behind its "+" toggle. Those are
 * rendered inline here: the toggle is not reproduced, and leaving the inputs out
 * would silently drop the values an existing file stores for them.
 */
function defineBlock(qName, symbol, attrs, colour, all) {
  // `_expandedDef` is the section MakeCode hides behind its "+" toggle, written
  // after `||` in the block string. Joining the two halves directly would run
  // the last label of one into the first of the other ("with buttonsvx"), so
  // they are separated explicitly.
  const expanded = attrs._expandedDef?.parts ?? [];
  const parts = [...(attrs._def.parts ?? [])];
  if (expanded.length > 0) {
    parts.push({ kind: 'label', text: ' ' }, ...expanded);
  }
  const parameters = symbol.parameters ?? [];

  const args = [];
  const shadows = {};
  const fieldDefaults = {};
  let message = '';

  for (const part of parts) {
    if (part.kind === 'label') {
      message += escapeMessage(part.text ?? '');
      continue;
    }
    if (part.kind === 'break') {
      message += '\n';
      continue;
    }
    if (part.kind !== 'param') {
      continue;
    }

    const parameter = parameters.find((p) => p.name === part.name);
    const shadowId = attrs._shadowOverrides?.[part.name] ?? part.shadowBlockId;
    const type = parameter?.type ?? 'any';

    args.push({
      type: 'input_value',
      name: part.name,
      ...(checkFor(type) ? { check: checkFor(type) } : {}),
    });
    message += `%${args.length}`;

    if (shadowId) {
      shadows[part.name] = {
        type: shadowId,
        value: attrs.paramDefl?.[part.name] ?? parameter?.initializer ?? undefined,
      };
    }
  }

  // A `() => void` parameter is an event body: it becomes a statement input, and
  // the block becomes top-level like MakeCode's `on game update`.
  const handler = parameters.find((p) => isHandler(p.type));
  if (handler) {
    for (const handlerParam of handler.handlerParameters ?? []) {
      // MakeCode stores these as HANDLER_DRAG_PARAM_<name>; declaring them keeps
      // an existing file's values from being dropped on load.
      args.push({
        type: 'field_variable',
        name: `HANDLER_DRAG_PARAM_${handlerParam.name}`,
        variable: handlerParam.name,
      });
      message += ` %${args.length}`;
      fieldDefaults[`HANDLER_DRAG_PARAM_${handlerParam.name}`] = handlerParam.name;
    }
    args.push({ type: 'input_statement', name: 'HANDLER' });
    message += ` %${args.length}`;
  }

  const definition = {
    type: attrs.blockId,
    message0: message.trim() === '' ? escapeMessage(qName) : message,
    ...(args.length > 0 ? { args0: args } : {}),
    colour,
    inputsInline: attrs.inlineInputMode !== 'external',
    tooltip: (attrs.jsDoc ?? '').split('\n')[0],
    helpUrl: attrs.help ? `https://arcade.makecode.com/reference/${attrs.help}` : '',
  };

  const returns = symbol.retType && symbol.retType !== 'void';
  if (handler) {
    // Event blocks sit loose on the canvas; they take no notches.
  } else if (returns) {
    const check = checkFor(symbol.retType);
    definition.output = check ?? null;
  } else {
    definition.previousStatement = null;
    definition.nextStatement = null;
  }

  void all;
  return { definition, shadows, fieldDefaults };
}

/**
 * Builds the dropdown blocks Arcade uses for enum and "kind" parameters.
 *
 * Two shapes exist. A plain enum (`Dimension`, `MoveKind`) becomes a dropdown of
 * its members. A *kind* (`SpriteKind`) is user-extensible — games define their
 * own kinds — so its dropdown is seeded with the built-in members and accepts
 * whatever else a file already contains.
 *
 * The field naming follows pxt's own convention as far as it could be confirmed
 * from the metadata. Where it turns out to differ, nothing is lost: the webview
 * keeps any field it does not recognize (see ensureFieldsExist in the webview),
 * so these blocks still round-trip.
 */
function buildEnumBlocks(all, namespaceMap) {
  const generated = [];
  const seen = new Set();

  // Kind blocks: a KIND_GET shim names the namespace holding its members.
  for (const symbol of Object.values(all)) {
    const attrs = symbol.attributes;
    if (attrs?.shim !== 'KIND_GET' || !attrs.blockId || seen.has(attrs.blockId)) {
      continue;
    }
    const kindNamespace = attrs.kindNamespace;
    const fieldName = attrs.kindMemberName ?? kindNamespace;
    const members = Object.entries(all)
      .filter(([qName, s]) => s.namespace === kindNamespace && s.attributes?.isKind)
      .map(([qName, s]) => [s.name ?? qName.split('.').pop(), qName]);
    if (members.length === 0) {
      continue;
    }
    seen.add(attrs.blockId);
    generated.push({
      type: attrs.blockId,
      message0: '%1',
      args0: [{ type: 'field_dropdown', name: fieldName, options: members }],
      colour: namespaceMap.get(symbol.namespace)?.colour ?? DEFAULT_COLOUR,
      output: 'Number',
      tooltip: attrs.jsDoc ?? `A ${kindNamespace} value.`,
      helpUrl: '',
    });
  }

  // Plain enums: members carry their own `block=` label.
  const enumMembers = new Map();
  for (const [qName, symbol] of Object.entries(all)) {
    if (!symbol.attributes?.block || symbol.attributes.blockId || !qName.includes('.')) {
      continue;
    }
    const owner = qName.slice(0, qName.lastIndexOf('.'));
    if (all[owner]?.kind !== KIND_ENUM) {
      continue;
    }
    if (!enumMembers.has(owner)) {
      enumMembers.set(owner, []);
    }
    enumMembers.get(owner).push([symbol.attributes.block, qName]);
  }

  for (const [enumName, members] of enumMembers) {
    const blockId = all[enumName]?.attributes?.blockId ?? enumName;
    if (seen.has(blockId) || members.length === 0) {
      continue;
    }
    seen.add(blockId);
    generated.push({
      type: blockId,
      message0: '%1',
      args0: [{ type: 'field_dropdown', name: blockId, options: members }],
      colour: namespaceMap.get(enumName.split('.')[0])?.colour ?? DEFAULT_COLOUR,
      output: 'Number',
      tooltip: all[enumName]?.attributes?.jsDoc ?? `A ${enumName} value.`,
      helpUrl: '',
    });
  }

  return generated;
}

/**
 * Arcade refers to shadow blocks that pxt implements as custom field editors
 * (image pickers, tilemap editors, sprite-kind dropdowns). Those editors are not
 * reproduced here, but every referenced shadow still needs *a* definition or
 * loading a file that uses it would fail, so anything left undefined gets a
 * plain text-field stand-in that preserves its value.
 */
function buildFallbackShadows(blocks, entries) {
  const defined = new Set(blocks.map((b) => b.type));
  const builtIn = new Set([
    'math_number',
    'math_integer',
    'math_whole_number',
    'text',
    'logic_boolean',
    'variables_get',
    'variables_set',
  ]);

  const referenced = new Set();
  for (const entry of entries) {
    for (const shadow of Object.values(entry.shadows)) {
      referenced.add(shadow.type);
    }
  }

  const extras = [];
  for (const type of referenced) {
    if (defined.has(type) || builtIn.has(type)) {
      continue;
    }
    extras.push({
      type,
      message0: '%1',
      args0: [{ type: 'field_input', name: 'value', text: '' }],
      colour: DEFAULT_COLOUR,
      output: null,
      tooltip: `${type} — this is a MakeCode field editor, shown here as a plain value you can edit as text.`,
      helpUrl: '',
    });
  }
  return extras;
}

function buildToolbox(entries, namespaceMap) {
  const byNamespace = new Map();
  for (const entry of entries) {
    if (!entry.listed) {
      continue;
    }
    if (!byNamespace.has(entry.namespace)) {
      byNamespace.set(entry.namespace, []);
    }
    byNamespace.get(entry.namespace).push(entry);
  }

  const categories = [];
  for (const [name, items] of byNamespace) {
    const namespace = namespaceMap.get(name);
    if (!namespace) {
      continue;
    }

    // MakeCode orders blocks by descending weight within each group, and groups
    // in the order the namespace declares them.
    const order = namespace.groups.length > 0 ? namespace.groups : [''];
    items.sort((a, b) => {
      const groupDelta = groupIndex(order, a.group) - groupIndex(order, b.group);
      return groupDelta !== 0 ? groupDelta : (b.weight ?? 50) - (a.weight ?? 50);
    });

    categories.push({
      name: namespace.label,
      namespace: name,
      colour: namespace.colour,
      icon: namespace.icon,
      weight: namespace.weight,
      advanced: namespace.advanced,
      blocks: items.map((item) => ({
        type: item.type,
        shadows: item.shadows,
        fields: item.fields,
      })),
    });
  }

  categories.sort((a, b) => {
    if (a.advanced !== b.advanced) {
      return a.advanced ? 1 : -1;
    }
    return b.weight - a.weight || a.name.localeCompare(b.name);
  });
  return categories;
}

function groupIndex(order, group) {
  const index = order.indexOf(group ?? '');
  return index === -1 ? order.length : index;
}

function isHandler(type) {
  return typeof type === 'string' && /=>\s*void\s*$/.test(type.replace(/\s+/g, ' '));
}

/** Blockly connection checks, kept to the types where they help and cannot misfire. */
function checkFor(type) {
  switch (type) {
    case 'number':
      return 'Number';
    case 'string':
      return 'String';
    case 'boolean':
      return 'Boolean';
    default:
      // Arcade's own types (Sprite, Image, tiles.Location…) are left unchecked:
      // pxt allows conversions Blockly's checker does not model, and a wrong
      // check silently refuses connections the user is entitled to make.
      return undefined;
  }
}

/** `%` and `$` are Blockly message placeholders and must be escaped in labels. */
function escapeMessage(text) {
  return text.replace(/%/g, '%%');
}

function capitalize(text) {
  return text.charAt(0).toUpperCase() + text.slice(1);
}
