/**
 * Turns MakeCode Arcade's compiled API metadata into Blockly block definitions
 * and a toolbox, so the editor renders real Arcade blocks — `sprite of kind`,
 * `on game update`, `move with buttons` — instead of generic placeholders.
 *
 * pxt has already parsed every block's layout into `attributes._def`, so this
 * translates that structure rather than re-parsing TypeScript annotations.
 *
 * Reads  .arcade-cache/target.json   (see scripts/fetchArcade.mjs)
 * Writes src/generated/arcade-blocks.json, arcade-toolbox.json, arcade-meta.json
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(root, 'src', 'generated');

/** pxt SymbolKind values this script cares about. */
const KIND_MODULE = 5;
const KIND_ENUM = 6;

const DEFAULT_COLOUR = '#7B8794';

const target = JSON.parse(await readFile(join(root, '.arcade-cache', 'target.json'), 'utf8'));

/** Every API symbol across all bundled packages, keyed by qualified name. */
const symbols = {};
/** Which package each symbol came from, to keep the toolbox to the defaults. */
const symbolPackage = new Map();
for (const [path, info] of Object.entries(target.apiInfo ?? {})) {
  // "libs/core---vm" and "libs/core" are the same package built for different
  // hardware; the base name is what the project's dependencies refer to.
  const pkg = path.replace(/^libs\//, '').split('---')[0];
  for (const [qName, symbol] of Object.entries(info.apis?.byQName ?? {})) {
    symbols[qName] = symbol;
    // Several packages extend the same namespace (an extension can add blocks to
    // `sprites`), so membership is tracked per symbol, not per namespace.
    symbolPackage.set(qName, pkg);
  }
}

/**
 * The packages a new Arcade project actually depends on.
 *
 * The bundle ships every optional extension too (corgio, darts, esp32, radio…).
 * Those are real Arcade blocks, but they are not in the default toolbox — a game
 * only gets them after adding the extension — so listing them would misrepresent
 * what Arcade offers. Their blocks stay *defined*, so a project that does use
 * them still loads; they are simply not offered in the toolbox.
 */
const defaultPackages = resolveDefaultPackages(target);
if (Object.keys(symbols).length === 0) {
  throw new Error('target bundle contained no API metadata');
}

const namespaces = collectNamespaces(symbols);
const { blocks, entries, skipped } = buildBlocks(symbols, namespaces);
// Dropdown blocks are described rather than defined: they are registered at
// runtime with a dynamic option list so unknown values can be added.
const dropdowns = buildEnumBlocks(symbols, namespaces);
const dropdownTypes = new Set(dropdowns.map((d) => d.type));
const extras = buildFallbackShadows(blocks, entries, dropdownTypes);
const toolbox = buildToolbox(entries, namespaces);

await mkdir(OUT, { recursive: true });
// A handful of symbols share a blockId across packages (different hardware
// variants defining the same block). Blockly keeps one definition per type, so
// pick the first deterministically rather than letting load order decide.
const deduped = [];
const seenTypes = new Set();
for (const block of [...blocks, ...extras]) {
  if (seenTypes.has(block.type)) {
    continue;
  }
  seenTypes.add(block.type);
  deduped.push(block);
}

await writeFile(join(OUT, 'arcade-blocks.json'), JSON.stringify(deduped, null, 0));
await writeFile(join(OUT, 'arcade-dropdowns.json'), JSON.stringify(dropdowns, null, 0));
await writeFile(join(OUT, 'arcade-toolbox.json'), JSON.stringify(toolbox, null, 0));
await writeFile(
  join(OUT, 'arcade-meta.json'),
  JSON.stringify(
    {
      target: target.id,
      targetVersion: target.versions?.target ?? null,
      pxtVersion: target.versions?.pxt ?? null,
      generatedBlocks: blocks.length,
      dropdownBlocks: dropdowns.length,
      fallbackShadows: extras.length,
      categories: toolbox.length,
      note: 'Generated by scripts/generateArcadeBlocks.mjs from the MakeCode Arcade target bundle.',
    },
    null,
    2
  )
);

console.log(`blocks:     ${blocks.length}`);
console.log(`dropdowns:  ${dropdowns.length} (${dropdowns.filter((d) => d.extensible).length} extensible)`);
console.log(`fallbacks:  ${extras.length}`);
console.log(`categories: ${toolbox.length}`);
console.log(`skipped:    ${skipped.length}`);

/** Namespaces carry the category colour, icon, ordering and group names. */
function resolveDefaultPackages(bundle) {
  const packages = bundle.bundledpkgs ?? {};
  const configOf = (name) => {
    try {
      return JSON.parse(packages[name]?.['pxt.json'] ?? '{}');
    } catch {
      return {};
    }
  };

  const roots = Object.keys(bundle.blocksprj?.config?.dependencies ?? { device: '*' });
  const closure = new Set();
  const pending = [...roots];
  while (pending.length > 0) {
    const name = pending.pop();
    if (closure.has(name) || !packages[name]) {
      continue;
    }
    closure.add(name);
    pending.push(...Object.keys(configOf(name).dependencies ?? {}));
  }
  return closure;
}

function collectNamespaces(all) {
  const found = new Map();
  for (const [qName, symbol] of Object.entries(all)) {
    if (symbol.kind !== KIND_MODULE || qName.includes('.')) {
      continue;
    }
    const attrs = symbol.attributes ?? {};
    found.set(qName, {
      name: qName,
      label: attrs.block ?? capitalize(qName),
      colour: attrs.color ?? DEFAULT_COLOUR,
      icon: attrs.icon ?? '',
      weight: attrs.weight ?? 50,
      advanced: Boolean(attrs.advanced),
      groups: attrs.groups ?? [],
      help: attrs.help ?? '',
    });
  }
  return found;
}

function buildBlocks(all, namespaceMap) {
  const blocks = [];
  const entries = [];
  const skipped = [];

  for (const [qName, symbol] of Object.entries(all)) {
    const attrs = symbol.attributes;
    if (!attrs?.blockId || !attrs.block || !attrs._def) {
      continue;
    }
    // Kind selectors are dropdowns over a user-extensible member list, built by
    // buildEnumBlocks; the generic path would give them a value socket instead.
    if (attrs.shim === 'KIND_GET') {
      continue;
    }

    const namespaceName = attrs.blockNamespace ?? qName.split('.')[0];
    const namespace = namespaceMap.get(namespaceName);
    const colour = attrs.color ?? namespace?.colour ?? DEFAULT_COLOUR;

    try {
      const block = defineBlock(qName, symbol, attrs, colour, all);
      blocks.push(block.definition);
      entries.push({
        type: attrs.blockId,
        namespace: namespaceName,
        package: symbolPackage.get(qName),
        group: attrs.group ?? '',
        weight: attrs.weight ?? 50,
        // Deprecated and hidden blocks are still *defined*, so existing files
        // that use them keep rendering — they are only left out of the toolbox.
        listed: !attrs.blockHidden && !attrs.deprecated && !attrs.debug,
        shadows: block.shadows,
        fields: block.fieldDefaults,
      });
    } catch (error) {
      skipped.push({ qName, reason: error.message });
    }
  }

  return { blocks, entries, skipped };
}

/**
 * Translates one pxt block definition into Blockly JSON.
 *
 * `_expandedDef` holds the parts MakeCode hides behind its "+" toggle. Those are
 * rendered inline here: the toggle is not reproduced, and leaving the inputs out
 * would silently drop the values an existing file stores for them.
 */
function defineBlock(qName, symbol, attrs, colour, all) {
  // `_expandedDef` is the section MakeCode hides behind its "+" toggle, written
  // after `||` in the block string. Joining the two halves directly would run
  // the last label of one into the first of the other ("with buttonsvx"), so
  // they are separated explicitly.
  const expanded = attrs._expandedDef?.parts ?? [];
  const parts = [...(attrs._def.parts ?? [])];
  if (expanded.length > 0) {
    parts.push({ kind: 'label', text: ' ' }, ...expanded);
  }
  const parameters = symbol.parameters ?? [];

  const args = [];
  const shadows = {};
  const fieldDefaults = {};
  let message = '';

  for (const part of parts) {
    if (part.kind === 'label') {
      message += escapeMessage(part.text ?? '');
      continue;
    }
    if (part.kind === 'break') {
      message += '\n';
      continue;
    }
    if (part.kind !== 'param') {
      continue;
    }

    const parameter = parameters.find((p) => p.name === part.name);
    const shadowId = attrs._shadowOverrides?.[part.name] ?? part.shadowBlockId;
    const type = parameter?.type ?? 'any';
    const editor = attrs.paramFieldEditor?.[part.name];

    if (editor) {
      // MakeCode draws these with a custom field editor — an image picker, a
      // speed slider, a colour swatch — and stores the value in a <field>, not
      // in a nested block. The editors themselves are not reproduced, but the
      // block must still carry a field of the same name or the value would have
      // nowhere to go.
      //
      // Only `paramFieldEditor` marks these. A `ref` param is a different
      // thing — a variable passed by reference, like
      // `$sprite=variables_get(mySprite)` — and keeps its value socket.
      args.push(fieldFor(part.name, editor, attrs.paramDefl?.[part.name]));
      message += `%${args.length}`;
      continue;
    }

    args.push({
      type: 'input_value',
      name: part.name,
      ...(checkFor(type) ? { check: checkFor(type) } : {}),
    });
    message += `%${args.length}`;

    if (shadowId) {
      shadows[part.name] = {
        type: shadowId,
        value: attrs.paramDefl?.[part.name] ?? parameter?.initializer ?? undefined,
      };
    }
  }

  // A `() => void` parameter is an event body: it becomes a statement input, and
  // the block becomes top-level like MakeCode's `on game update`.
  const handler = parameters.find((p) => isHandler(p.type));
  if (handler) {
    for (const handlerParam of handler.handlerParameters ?? []) {
      // MakeCode stores these as HANDLER_DRAG_PARAM_<name>; declaring them keeps
      // an existing file's values from being dropped on load.
      args.push({
        type: 'field_variable',
        name: `HANDLER_DRAG_PARAM_${handlerParam.name}`,
        variable: handlerParam.name,
      });
      message += ` %${args.length}`;
      fieldDefaults[`HANDLER_DRAG_PARAM_${handlerParam.name}`] = handlerParam.name;
    }
    args.push({ type: 'input_statement', name: 'HANDLER' });
    message += ` %${args.length}`;
  }

  const definition = {
    type: attrs.blockId,
    message0: message.trim() === '' ? escapeMessage(qName) : message,
    ...(args.length > 0 ? { args0: args } : {}),
    colour,
    inputsInline: attrs.inlineInputMode !== 'external',
    tooltip: (attrs.jsDoc ?? '').split('\n')[0],
    helpUrl: attrs.help ? `https://arcade.makecode.com/reference/${attrs.help}` : '',
  };

  const returns = symbol.retType && symbol.retType !== 'void';
  if (handler) {
    // Event blocks sit loose on the canvas; they take no notches.
  } else if (returns) {
    const check = checkFor(symbol.retType);
    definition.output = check ?? null;
  } else {
    definition.previousStatement = null;
    definition.nextStatement = null;
  }

  void all;
  return { definition, shadows, fieldDefaults };
}

/**
 * Builds the dropdown blocks Arcade uses for enum and "kind" parameters.
 *
 * Two shapes exist. A plain enum (`Dimension`, `MoveKind`) becomes a dropdown of
 * its members. A *kind* (`SpriteKind`) is user-extensible — games define their
 * own kinds — so its dropdown is seeded with the built-in members and accepts
 * whatever else a file already contains.
 *
 * The field naming follows pxt's own convention as far as it could be confirmed
 * from the metadata. Where it turns out to differ, nothing is lost: the webview
 * keeps any field it does not recognize (see ensureFieldsExist in the webview),
 * so these blocks still round-trip.
 */
function buildEnumBlocks(all, namespaceMap) {
  const generated = [];
  const seen = new Set();

  // Kind blocks. Symbols carry no `namespace`/`name` of their own in this
  // serialization, so both are derived from the qualified name.
  for (const [qName, symbol] of Object.entries(all)) {
    const attrs = symbol.attributes;
    if (attrs?.shim !== 'KIND_GET' || !attrs.blockId || seen.has(attrs.blockId)) {
      continue;
    }
    const kindNamespace = attrs.kindNamespace ?? qName.split('.')[0];
    // Confirmed against a file saved by Arcade: the field is always MEMBER and
    // holds the bare member name ("Player"), not the qualified one. The
    // metadata's `kindMemberName` names the TypeScript parameter, which is a
    // different thing and does not appear in the XML.
    const fieldName = 'MEMBER';
    const members = Object.entries(all)
      .filter(([member, s]) => s.attributes?.isKind && member.startsWith(`${kindNamespace}.`))
      .map(([member]) => {
        const bare = member.slice(kindNamespace.length + 1);
        return [bare, bare];
      });
    if (members.length === 0) {
      continue;
    }
    seen.add(attrs.blockId);
    generated.push({
      type: attrs.blockId,
      field: fieldName,
      options: members,
      // Games define their own kinds (SpriteKind.Enemy, SpriteKind.Coin), so the
      // dropdown has to accept values that are not in this list.
      extensible: true,
      // Arcade declares each kind as a workspace variable of this type, and that
      // list — not the metadata — is what a given game actually offers.
      variableType: `KIND_${kindNamespace}`,
      colour: namespaceMap.get(qName.split('.')[0])?.colour ?? DEFAULT_COLOUR,
      tooltip: attrs.jsDoc ?? `A ${kindNamespace} value.`,
    });
  }

  // Plain enums: members carry their own `block=` label.
  const enumMembers = new Map();
  for (const [qName, symbol] of Object.entries(all)) {
    if (!symbol.attributes?.block || symbol.attributes.blockId || !qName.includes('.')) {
      continue;
    }
    const owner = qName.slice(0, qName.lastIndexOf('.'));
    if (all[owner]?.kind !== KIND_ENUM) {
      continue;
    }
    if (!enumMembers.has(owner)) {
      enumMembers.set(owner, []);
    }
    enumMembers.get(owner).push([symbol.attributes.block, qName]);
  }

  for (const [enumName, members] of enumMembers) {
    const blockId = all[enumName]?.attributes?.blockId ?? enumName;
    if (seen.has(blockId) || members.length === 0) {
      continue;
    }
    seen.add(blockId);
    generated.push({
      type: blockId,
      field: blockId,
      options: members,
      extensible: false,
      colour: namespaceMap.get(enumName.split('.')[0])?.colour ?? DEFAULT_COLOUR,
      tooltip: all[enumName]?.attributes?.jsDoc ?? `A ${enumName} value.`,
    });
  }

  return generated;
}

/**
 * Arcade refers to shadow blocks that pxt implements as custom field editors
 * (image pickers, tilemap editors, sprite-kind dropdowns). Those editors are not
 * reproduced here, but every referenced shadow still needs *a* definition or
 * loading a file that uses it would fail, so anything left undefined gets a
 * plain text-field stand-in that preserves its value.
 */
function buildFallbackShadows(blocks, entries, dropdownTypes) {
  const defined = new Set([...blocks.map((b) => b.type), ...dropdownTypes]);
  const builtIn = new Set([
    'math_number',
    'math_integer',
    'math_whole_number',
    'text',
    'logic_boolean',
    'variables_get',
    'variables_set',
  ]);

  const referenced = new Set();
  for (const entry of entries) {
    for (const shadow of Object.values(entry.shadows)) {
      referenced.add(shadow.type);
    }
  }

  const extras = [];
  for (const type of referenced) {
    if (defined.has(type) || builtIn.has(type)) {
      continue;
    }
    extras.push({
      type,
      message0: '%1',
      args0: [{ type: 'field_input', name: 'value', text: '' }],
      colour: DEFAULT_COLOUR,
      output: null,
      tooltip: `${type} — this is a MakeCode field editor, shown here as a plain value you can edit as text.`,
      helpUrl: '',
    });
  }
  return extras;
}

function buildToolbox(entries, namespaceMap) {
  const byNamespace = new Map();
  for (const entry of entries) {
    if (!entry.listed) {
      continue;
    }
    // Blocks from optional extensions stay defined but are not offered.
    if (entry.package && !defaultPackages.has(entry.package)) {
      continue;
    }
    if (!byNamespace.has(entry.namespace)) {
      byNamespace.set(entry.namespace, []);
    }
    byNamespace.get(entry.namespace).push(entry);
  }

  const categories = [];
  for (const [name, items] of byNamespace) {
    const namespace = namespaceMap.get(name);
    if (!namespace) {
      continue;
    }


    // MakeCode orders blocks by descending weight within each group, and groups
    // in the order the namespace declares them.
    const order = namespace.groups.length > 0 ? namespace.groups : [''];
    items.sort((a, b) => {
      const groupDelta = groupIndex(order, a.group) - groupIndex(order, b.group);
      return groupDelta !== 0 ? groupDelta : (b.weight ?? 50) - (a.weight ?? 50);
    });

    categories.push({
      name: namespace.label,
      namespace: name,
      colour: namespace.colour,
      icon: namespace.icon,
      weight: namespace.weight,
      advanced: namespace.advanced,
      blocks: items.map((item) => ({
        type: item.type,
        shadows: item.shadows,
        fields: item.fields,
      })),
    });
  }

  categories.sort((a, b) => {
    if (a.advanced !== b.advanced) {
      return a.advanced ? 1 : -1;
    }
    return b.weight - a.weight || a.name.localeCompare(b.name);
  });
  return categories;
}

function groupIndex(order, group) {
  const index = order.indexOf(group ?? '');
  return index === -1 ? order.length : index;
}

function isHandler(type) {
  return typeof type === 'string' && /=>\s*void\s*$/.test(type.replace(/\s+/g, ' '));
}

/**
 * A stand-in for one of MakeCode's custom field editors. Numeric editors get a
 * number field so arithmetic still reads naturally; everything else gets text,
 * which can hold any value the file contains.
 */
function fieldFor(name, editor, defaultValue) {
  const numeric = ['speed', 'colornumber', 'colorindex', 'number', 'numberdropdown', 'timePicker'];
  if (numeric.includes(editor)) {
    const parsed = Number(String(defaultValue ?? '').replace(/["']/g, ''));
    return { type: 'field_number', name, value: Number.isFinite(parsed) ? parsed : 0 };
  }
  return {
    type: 'field_input',
    name,
    text: String(defaultValue ?? '').replace(/^["'](.*)["']$/, '$1'),
  };
}

/** Blockly connection checks, kept to the types where they help and cannot misfire. */
function checkFor(type) {
  switch (type) {
    case 'number':
      return 'Number';
    case 'string':
      return 'String';
    case 'boolean':
      return 'Boolean';
    default:
      // Arcade's own types (Sprite, Image, tiles.Location…) are left unchecked:
      // pxt allows conversions Blockly's checker does not model, and a wrong
      // check silently refuses connections the user is entitled to make.
      return undefined;
  }
}

/** `%` and `$` are Blockly message placeholders and must be escaped in labels. */
function escapeMessage(text) {
  return text.replace(/%/g, '%%');
}

function capitalize(text) {
  return text.charAt(0).toUpperCase() + text.slice(1);
}
